#!/usr/bin/env bash
set -e

openCover() {
	local coverPath=${1:?"cover file path"}
	trap 'rm "'"${coverPath}"'"' EXIT
	go tool cover -html="${coverPath}"
}
export -f openCover

test-go -cover -coverprofile=coverage.txt -covermode=atomic
find . -type f -name 'coverage.txt' -exec bash -c 'openCover "$@"' bash {} \;
