#!/usr/bin/env bash
set -euo pipefail
shopt -s nullglob
shopt -s globstar

(
    type go
) 1>/dev/null

main() (
    local gmpath path
    for gmpath in ./**/go.mod; do
        path=${gmpath%"go.mod"}
        cd "${path}"
        testCurrent "${@}"
    done
)

testCurrent() {
    go test ./... -race -count 1 -bench '^BenchmarkTest' "${@}"
}

main "${@}"
